[package]
name = "spx"
version = "0.1.0"
authors = ["russellb23 <bertrussell23@yahoo.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4"
